### PR TITLE
#164102803 Designed the landing page mockup

### PR DESCRIPTION
**Pull request by filschristian**
#### What does this PR do?
Have the design for the landing page

#### Description of Task to be completed?

- Design the landing page

- Add responsiveness to support mobile and tablet devices.

#### How should this be manually tested?
* git clone
* npm install
* npm run build-scss
* open .ui/
#### Any background context you want to provide?

- [Desktop Version Mockups](https://drive.google.com/drive/u/1/folders/1lcFZ3-tOAoN8g5_e6ORaKs8jEVI783jg)

- [Mobile and Tablet version Mockups](https://drive.google.com/drive/u/1/folders/1chupPda0Ny-iePagVr0_QCZgEhBabhM_)

#### What are the relevant pivotal tracker stories?
#164102803
#### Screenshots (if appropriate)
image

image

#### Questions:
N/A

### CODE REVIEW

**Review by Nziranziza — APPROVED** [review]

**Review by oesukam — CHANGES_REQUESTED** [review]
@filschristian Try ton reduce article's image and text size to be the same as the mockup
image

**Comment by kimotho-njoki** [comment]
@filschristian was @oesukam's comment worked on?

**Comment by filschristian** [comment]
> @filschristian was @oesukam's comment worked on?

@kimotho-njoki  I am working on it right now... Will be done with it in few mins

**Comment by filschristian** [comment]
> @filschristian Try ton reduce article's image and text size to be the same as the mockup
> ![image](https://user-images.githubusercontent.com/17350127/53359605-05d24c80-393c-11e9-99d9-052f9e502897.png
@oesukam Check the new image of the mobile version

**Review by oesukam — CHANGES_REQUESTED** [review]
@filschristian Article's image should also have rounded corners as suggested by the PO

**Comment by filschristian** [comment]
> @filschristian Article's image should also have rounded corners as suggested by the PO

Done. Check new images in the PR description @oesukam

**Review by oesukam — APPROVED** [review]
@filschristian  All request changes have been applied. The PR is approved and can be merged after resolving merge conflicts

**Pull request merged**
